[build]
  command = "echo 'Static deploy'"
  publish = "."

[env]
  ADMIN_PASSWORD = "rock"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { ADMIN_PASSWORD = "rock" }
